# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a5dc33da09cbeb938b1a4e61a42feb031d5119f2db6564240b759f6c9431e5c47e5440f4c86a942ad28654d866ecab0cb249379853bacaf6af5c64d3e8214e5d

test:
  secret_key_base: 2d930f8c8b490748a1d9ac5f4b15624e8149c278698496f19766d87827c6c9179ad15620f01a6970170ea556c2efa97d8f0909c2c027f276924af3f01e3bf00d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
